### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iceblue25** [davidavdav/IVectors.jl#1]
Is there documentation on how to use this package? Is it still under development? Any chance for a better license like MIT?

Thanks

**Comment by davidavdav** [comment]
There is no documentation yet, because it is very in a development stage---but at the moment I don't see this happening form my side.  The package is based on using the GaussianMixtures infrastructure.  But as you can see, there isn't much done yet.  Ideally this package would be compatible with the work described [here](http://voicebiometry.org/download/interspeech2015-vbs-technical-description.pdf).

I wasn't aware of a moral scale of how to evaluate licenses for goodness.  Could you please elaborate on that?

**Comment by iceblue25** [comment]
Thanks for the link. Interesting read about the initiative. 

MIT is better in a corporate environment in the sense that can be compatible with a variety of licenses. Function calls to GPL can dictate to release the entire code under GPL license which makes some people (especially in corporations) to avoid using any GPL code. I m not a lawyer but that is what I understand.
Having said that it is up to you to release your software in any license you wish.

**Comment by davidavdav** [comment]
The licence has been changed to a Better Licence in d05680c0b67374cb73ebdc9e0cf73c3aef77969c, documentation was added in be851216f04cfa70116484cd37d8f311c59f635b .

**Comment by iceblue25** [comment]
Funny license name and appreciated!
